### ISSUE TITLE
Question: enable Arm energy probe (AEP) in ipython script

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/lisa#1742]
I want to enable AEP in the ipython script, and then invoke the functions to reset meter and record the meter for a specific workload.  If I remember correctly, there have two interfaces for enabling AEP, one is the LISA's self interface and another is based on devlib.  So I am not clear what's a good practice to enable AEP in ipython script.

I searched a bit for the document, it just gives out the suggestion for using the below configurations:

```
# AEP Energy Meter configuration
aep-conf:
    # Channels to use
    # type: Mapping
    channel-map: ['Device0' : 'BAT']

    # Resistor values
    # type: TypedList[float]
    resistor-values: [0.033]

    # List of labels
    # type: TypedList[str]
    labels: ['aep']

    # TTY device
    # type: TypedList[str]
    device-entry: ['/dev/ttyACM0']
```

If this is the good way to enable AEP, then what's the function I should use in ipython script for energy measurement?  thanks for suggestions!
